@startuml
'https://plantuml.com/use-case-diagram

left to right direction
User <<Registered user>>
User --> (View all books in library)
User --> (Search for books)
User --> (Take book)
User --> (Return book)
User --> (View his books)

Admin <<Librarian>>
Admin --> (Add books to library)
Admin --> (Delete books from library)
Admin --> (View all books in library)
Admin --> (Search for books)

Unreg << Unregistered user>>
Unreg ---> (View all books in library)
Unreg ---> (Search for books)
Unreg -> (Log in)
@enduml